# Low Poly Colorizer — Godot import notes

Generated by Low Poly Colorizer (LPC).
<https://github.com/wasdcat/low-poly-colorizer> — a WASDCAT Games project.

This folder holds the shaders, materials, and **two data textures** for the
LPC look in Godot 4. The two PNGs are **not ordinary color textures** — the
shaders sample their raw pixel values directly, so Godot's default texture
import (lossy VRAM compression, mipmaps) corrupts them. Set the parameters
below **once per texture**; they are saved in the sidecar `.import` file and
survive future re-exports (the filenames stay stable).

Select a texture in the **FileSystem** dock → **Import** tab → set the values,
then click **Reimport**.

## Both textures — `{{prefix}}palette.png` and `{{prefix}}preset_lut.png`

- **Detect 3D → Compress To = Disabled**
  The single most important setting. Otherwise Godot silently re-imports the
  texture as **lossy VRAM compression** the moment it is first used in a 3D
  material — this shifts every palette color and mangles the packed PBR
  values (presets look ignored/wrong).
- **Compress → Mode = Lossless**
  Keeps the pixel values byte-exact, so what Godot samples matches the Blender
  preview.
- **Mipmaps → Generate = Off**
  A data texture must never blend across neighboring cells / presets.

Filtering is already forced to **Nearest** by the shaders' `filter_nearest`
sampler hint, so you do not need to set it on the texture itself.

## Additionally for `{{prefix}}preset_lut.png` only

- **Process → Fix Alpha Border = Off**
  This LUT packs four *unrelated* scalars into R/G/B/A
  (roughness / metallic / clearcoat / emission) — **alpha is not
  transparency**. Fix Alpha Border (on by default) overwrites the RGB of every
  texel whose alpha is `0` (i.e. every preset with `emission = 0`, the common
  case) with a neighbor's color, destroying roughness/metallic/clearcoat for
  those presets.

## Symptom → cause

- **Colors in Godot look completely different from the Blender preview** →
  `{{prefix}}palette.png` got VRAM-compressed: set **Detect 3D → Compress To =
  Disabled** and **Compress → Mode = Lossless**, then Reimport.
- **Presets (metallic / roughness / clearcoat) are ignored or wrong** →
  `{{prefix}}preset_lut.png` still has **Fix Alpha Border** on, or was
  VRAM-compressed: fix both settings above, then Reimport.

## Assigning the material

The geometry with its per-face data reaches Godot separately via the `.blend`
import (the palette cell / preset position travel in the mesh's UV maps). On
the imported mesh, set the surface's **Material Override** to
`{{prefix}}multicolor.tres`. For meshes **not** painted in the add-on, use
`{{prefix}}singlecolor.tres` and set its per-instance shader parameters in the
`MeshInstance3D` inspector.
