# SPDX-FileCopyrightText: 2026 Frank Winter <https://www.frankwinter.com/>
# SPDX-License-Identifier: MIT
#
# This file was generated by Low Poly Colorizer (LPC). <https://github.com/wasdcat/low-poly-colorizer>
# A WASDCAT Games project. <https://www.wasdcat.com/>

class_name {{prefix_pascal}}SinglecolorResource
extends Resource

## One named look for the {{prefix}}singlecolor material (Godot 4): a palette
## cell, a preset, and an optional emission override -- exactly the four
## per-instance values that shader takes.
##
## Save looks as .tres files ("Gold", "SignalRed", ...) and hand them around
## like any other resource: a signal node with a `stop` and a `go` slot calls
## [method apply_to] on its lamp whenever it switches.
##
## These are [b]instance[/b] uniforms -- they live on the MeshInstance3D, not
## on the material, which is why every instance can show a different look while
## they all share the one {{prefix}}singlecolor.tres. [method apply_to] takes
## the node for that reason, and there is deliberately nothing here that touches
## the material: writing into it would change the look of every instance using
## it, and this script holds no reference to it at all, so it stays independent
## of where the exported files end up in your project.
##
## Regenerated on every export -- do not edit. The .tres files you author from
## it are yours and are never touched.


## The presets as they existed at the last export, by list position -- the
## value the shader's `lpc_preset_position` takes.
##
## Re-exporting after adding, deleting or [b]reordering[/b] presets rewrites
## this block. Code written against a member name ([code]Preset.EMISSION[/code])
## follows the change automatically; an already-authored .tres stores the plain
## int, so a reorder silently repoints it at whatever preset now sits at that
## position. Renaming is safe either way.
enum Preset {
{{preset_enum}}
}


## Palette column, in the same numbering the picker and the shader's
## `lpc_palette_cell_x` use.
@export_range(0, {{palette_cols_max}}) var palette_cell_x: int = 0

## Palette row, in the same numbering the picker and the shader's
## `lpc_palette_cell_y` use.
@export_range(0, {{palette_rows_max}}) var palette_cell_y: int = 0

## Which preset supplies roughness / metallic / clearcoat / emission.
@export var preset: Preset = Preset.{{preset_enum_first}}

## -1.0 keeps the preset's own emission; any other value overrides it. This is
## the lamp-on / lamp-off switch when two looks differ in nothing else.
@export_range(-1.0, 1.0) var emission_override: float = -1.0


## Push this look onto [param instance] -- a MeshInstance3D (or any other
## GeometryInstance3D) whose material is {{prefix}}singlecolor.tres.
##
## Assigning that material is up to you (Material Override in the inspector, or
## your own code). If the instance runs a different shader, these writes go
## nowhere: nothing errors, the look simply has no effect.
##
## Cheap enough to call on every state change: four per-instance parameter
## writes, no material duplication, no shader recompile.
##
## The uniform names below are literal on purpose. They are part of the shader's
## own source text, not of the export's configurable namespace, so they do not
## follow the file-name prefix.
func apply_to(instance: GeometryInstance3D) -> void:
	instance.set_instance_shader_parameter(&"lpc_palette_cell_x", palette_cell_x)
	instance.set_instance_shader_parameter(&"lpc_palette_cell_y", palette_cell_y)
	instance.set_instance_shader_parameter(&"lpc_preset_position", preset)
	instance.set_instance_shader_parameter(&"lpc_emission_override", emission_override)
