schema_version = "1.0.0"

id = "low_poly_colorizer"
version = "0.1.1"
name = "Low Poly Colorizer"
tagline = "Face-Material-Painting mit Paletten-Picker und Godot-Export"
maintainer = "Frank Winter <studio@frankwinter.com>"
type = "add-on"

tags = ["Material", "Paint", "Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
